/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 6.0_1 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=78ca7e82b9b0d602750bcda084a7b41d (do not edit this line) */
