/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 6.0_1 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMUL = 4;
  public int JJTDIV = 5;
  public int JJTTERM = 6;
  public int JJTSIGN = 7;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
    "Sign",
  };
}
/* JavaCC - OriginalChecksum=b57c0e7650a937a1e13ed49e9a18f368 (do not edit this line) */
